config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  mount Slack::API => '/'

  root "slack_posts#index"

  resources :slack_posts, only: [:index] do
    resources :events, only: [:new]

    member do
      post :discard
    end
  end

  resources :events, only: [:create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :slack_post
end

app/models/slack_post.rb
class SlackPost < ApplicationRecord
  has_one :event

  scope :discarded, -> { where(discarded: true) }
  scope :remaining, -> { includes(:event).where(discarded: false, events: { id: nil }) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    slack_post = SlackPost.find(params[:slack_post_id])
    redirect_to slack_posts_path unless slack_post

    @event = slack_post.build_event
  end

  def create
    event = Event.new(create_params)

    if event.save
      redirect_to slack_posts_path
    end
  end

  private

  def create_params
    params.require(:event)
      .permit(:title, :start_time, :end_time, :slack_post_id)
  end
end

app/controllers/slack_posts_controller.rb
class SlackPostsController < ApplicationController
  def index
    @slack_posts = SlackPost.remaining
  end

  def discard
    slack_post = SlackPost.find(params[:id])

    if slack_post.update(discarded: true)
      redirect_to slack_posts_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/new.html.erb
<h1>Create a new event</h1>

<%= form_with model: @event, class: 'form-container', id: dom_id(@event) do |form| %>
  <div class="form-input">
    <%= form.label :title, 'Name of the event' %>
    <%= form.text_field :title %>
  </div>

  <div class="form-input">
    <%= form.label :start_time, 'Begining' %>
    <div class="form-input-datetime-select">
      <%= form.datetime_select :start_time,
        selected: Time.zone.now,
        minute_step: 5,
        start_year: Time.zone.now.year,
        end_year: Time.zone.now.year + 1,
        order: %i[day month year hour minute]
      %>
    </div>
  </div>

  <div class="form-input">
    <%= form.label :end_time, 'End' %>
    <div class="form-input-datetime-select">
      <%= form.datetime_select :end_time,
        include_blank: true,
        minute_step: 5,
        start_year: Time.zone.now.year,
        end_year: Time.zone.now.year + 1,
        order: %i[day month year hour minute]
      %>
    </div>
  </div>

  <%= form.hidden_field :slack_post_id %>

  <div class="form-buttons">
    <%= form.submit 'Create', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NomadCounter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <% if Rails.env.development? %>
      <%= javascript_include_tag "hotwire-livereload", defer: true %>
    <% end %>
  </head>

  <body class="bg-background flex flex-col h-screen justify-between">
    <%= render partial: 'shared/header' %>

    <div class="grid grid-cols-6 gap-4 my-8 mb-auto justify-evenly">
      <%= render partial: 'shared/navigation', class: 'col-span-2' %>

      <main class="col-span-4 m-2 w-full">
        <%= yield %>
      </main>
    </div>

    <%= render partial: 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="flex justify-center h-20 border-t border-t-zinc-400">
  <span class="m-4">© 2022 brindu</span>
</footer>

app/views/shared/_header.html.erb
<header class="border-b border-b-zinc-400 h-20 flex items-center">
  <span class="m-8 text-2xl font-bold">Nomad Counter</span>
</header>

app/views/shared/_navigation.html.erb
<nav>
  <ul>
    <li class="my-2 px-4">
      <a href="#"><span class="nav-link">Incoming events</span></a>
    </li>
    <li class="my-2 px-4">
      <a href="#"><span class="nav-link">New Slack posts</span></a>
    </li>
  </ul>
</nav>

app/views/slack_posts/_slack_post.html.erb
<div class="shadow-md border border-secondary-200 p-2 rounded-md" id="<%= dom_id(slack_post) %>">
  <ul class="flex gap-2 text-sm mb-2 p-1 border-b border-b-secondary-200">
    <li>
      At: <%= slack_post.timestamp %>
    </li>
    <li>
      Posted by: <%= slack_post.user_id %>
    </li>
    <li>
      In channel: <%= slack_post.channel_id %>
    </li>
  </ul>

  <p class="my-4"><%= slack_post.text %></p>

  <ul class="flex gap-4 justify-end">
    <%= button_to 'Create event', new_slack_post_event_path(slack_post), method: :get, id: 'add_event', class: 'btn btn-primary' %>
    <%= button_to 'Discard', discard_slack_post_path(slack_post), method: :post, id: 'discard', class: 'btn btn-secondary' %>
  </ul>
</div>

app/views/slack_posts/index.html.erb
<h1 class="text-xl mb-4">Newly Published Slack Posts</h1>

<% if @slack_posts %>
  <div class="flex flex-col gap-4">
    <% @slack_posts.each do |post| %>
      <%= render post %>
    <% end %>
  </div>
<% end %>

app/views/slack_posts/unpublished.html.erb
<h1 class="text-xl mb-4">Newly Published Slack Posts</h1>

<% if @slack_posts %>
  <div class="flex flex-col gap-4">
    <% @slack_posts.each do |post| %>
      <%= render post %>
    <% end %>
  </div>
<% end %>